### ISSUE TITLE
Add HashableStruct type

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#2428]
### Issue to be solved

Currently there is no type exposed to Cadence programs which represents the type that can be used as a `Dictionary` key type.

### Suggested Solution

```[tasklist]
### Tasks
- [ ] Add a `HashableStruct` interface, subtype of `AnyStruct`
- [ ] Have all types mentioned in `IsValidDictionaryKeyType` conform to `HashableStruct`
- [ ] Replace `IsValidDictionaryKeyType` with a subtype check for `HashableStruct`
```

**Comment by turbolent** [comment]
No, this feature has not been added yet, contributions are very welcome

**Comment by PratikDhanave** [comment]
@PratikDhanave thank you I can see in pratt parser is used for parsing is there any developer documentation available please share it with me ?

**Comment by turbolent** [comment]
@PratikDhanave Sorry, I'm not quite understanding what you are asking for. Are you asking for general developer documentation, or specifically for the operator precedence logic in the parser?

BTW, for this issue, there is no work in the parser necessary, just in the type checker and interpreter.

**Comment by PratikDhanave** [comment]
hi @turbolent thank you for info I am working on it

**Comment by PratikDhanave** [comment]
hi @turbolent is this correct ?
``// HashableStruct
type HashableStruct AnyStructType

var TheHashableStructType = HashableStruct{}

func NewTheHashableStruct() HashableStruct {
	return TheHashableStructType
}

func (HashableStruct) isType() {}

func (HashableStruct) ID() string {
	return "HashableStruct"
}

func (t HashableStruct) Equal(other Type) bool {
	return t == other
} ``

**Comment by turbolent** [comment]
@PratikDhanave That should be it for the `cadence` package, yeah. `type HashableStruct AnyStructType` should be `type HashableStruct struct{}` though

**Comment by PratikDhanave** [comment]
@turbolent thank you for your feedback.

**Comment by darkdrag00nv2** [comment]
I'll pick this up unless @PratikDhanave is actively working on it.

**Comment by darkdrag00nv2** [comment]
@turbolent What should be the interface definition?

```cadence
pub struct interface HashableStruct {
    pub fun hash(): [UInt8]
}
```

Since the sema generator doesn't support interface, I'll model it in Go.

**Comment by turbolent** [comment]
Eventually, a type similar to this would be nice to have, as it would allow developers to make their types hashable / usable as dictionary keys. 

As a start, it would be nice to just have a type `HashableStruct`, and only the currently built-in types that are hashable are "hardcoded" to be subtypes of `HashableStruct`. 

Later, this type could become an interface, and thus implementable by developers for their types. However, that requires some more work. Unlike in other languages, which require an implementation of a function like `fun hash(): [UInt8]`, there is an additional requirement for the hash value: The hash value is prefixed with a type indicator. For example, if you look at the implementations of `interpreter.HashableValue`, the implementations of the `HashInput` function prefix the result with a `HashInputType`. This would need to be made user-extendable.

(@fxamacker can you remind me why we want the type prefix/indicator? Unfortunately, I don't seem to have documented it and don't remember either)

**Comment by fxamacker** [comment]
> (@fxamacker can you remind me why we want the type prefix/indicator? Unfortunately, I don't seem to have documented it and don't remember either)

@turbolent 

Having a type prefix/indicator in hash input is to reduce hash collisions.

Different types can have same hash input value if we don't include the type prefix.  For example, `UInt8(0)` and `UInt64(0)`) would produce same hash digest if we don't include type prefix as hash input.  Same with other bit patterns of same length (e.g. 4-byte string can match any other 4-byte hash input of different type).

If users are allowed to provide entire hash input, would that make it easier for users to intentionally or accidentally cause numerous hash collisions?

**Comment by turbolent** [comment]
@fxamacker I see, thanks for the reminder, great explanation! I guess if we let user types to become hashable, we neither want to burden developers with having to manually include type information to avoid collisions, nor want to let user code intentionally omit them so they can cause many collisions.
