### ISSUE TITLE
Add purity annotations to newly added functions

### ISSUE THREAD

**Issue by SupunS** [onflow/cadence#2466]
### Issue to be solved

There are some native function types added to the `master` branch, after the purity annotation change was added in `stable-cadence`. e.g: 
- [x] [Address.fromBytes()](https://github.com/onflow/cadence/pull/2452)

When the stable-cadence branch is synced/merged to `master`, ensure these newly added functions have the proper purity annotation.

### Suggested Solution

Scan through all the newly added functions, and added annotations as required.
```[tasklist]
### Tasks
- [x] `String.join` added in #2762
- [x] `String.split` added in #2791
```

**Comment by j1010001** [comment]
Do one last pass before the 1.0 release.
