### ISSUE TITLE
Add a `Range<T: Integer>` type and allow in for-loop

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#2482]
- [x] Add a new built-in type `Range`:

  ```
  struct Range<T: Integer> {
     let start: T
     let endInclusive: T
  }
  ```

- [x] Add support for iterating over `Range` in for-in statements
```[tasklist]
### Tasks
- [ ] https://github.com/onflow/cadence/issues/2885
- [ ] https://github.com/onflow/cadence/issues/2884
- [ ] https://github.com/onflow/cadence/issues/2886
- [ ] https://github.com/onflow/cadence/issues/2870
- [ ] https://github.com/onflow/cadence/issues/2871
```

**Comment by turbolent** [comment]
Before starting an implementation, we should discuss the design and publish a proper design document, potentially a FLIP.

**Comment by bluesign** [comment]
Maybe it is good time to expose built in interfaces (comparable, enumerable etc) to Cadence. Also ‘step’ here can be useful too. ( reverse ranges especially)

**Comment by turbolent** [comment]
It might be a good idea to include the concept of a step, but for the concept of a range, that seems a bit odd.

For example, in [Kotlin](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.ranges/-int-range/-init-.html), [Swift](https://developer.apple.com/documentation/swift/range), and [Rust](https://doc.rust-lang.org/std/ops/struct.Range.html), ranges do not have a step.

Instead, some languages have a separate concept for [progression](https://en.wikipedia.org/wiki/Arithmetic_progression), e.g. Kotlin has [`Progression`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.ranges/-int-progression/), and Swift has [`StrideThrough`](https://developer.apple.com/documentation/swift/stridethrough). It looks like Rust has the concept of a "wrapper iterator" that allows stepping, [`StepBy`](https://doc.rust-lang.org/std/iter/struct.StepBy.html).

Maybe we can start with a simple `Range`, and then follow up with a progression type.

**Comment by bluesign** [comment]
Are we planning ranges to be Values? If so we also need to discuss about the API they will have.

**Comment by turbolent** [comment]
@bluesign Yes, see the description

**Comment by darkdrag00nv2** [comment]
Kotlin ranges only have two member functions:

1. `contains<T>(value: T)`: Check if T belongs in the Range
2. `isEmpty()`: Checks if the Range is empty

They inherit a lot of functions from Iterable such as `any`, `all`, `distinct`, `drop`, `filter`, ... but I think if we wish to support these, they should first be added in `Array`. So may be we should only add the above two functions in `Range` for now.

**Comment by bluesign** [comment]
I think we need to expose somehow; `next()`  or similar functions as this is iterator. I am thinking maybe more python way, but `range` , `stride` etc feels more like generators to me. `contains` is pretty cool. `isEmpty` probably can be replaced with `length`.

**Comment by darkdrag00nv2** [comment]
> For example, in [Kotlin](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.ranges/-int-range/-init-.html), [Swift](https://developer.apple.com/documentation/swift/range), and [Rust](https://doc.rust-lang.org/std/ops/struct.Range.html), ranges do not have a step.

@turbolent Actually `Range` in Kotlin does have a `step`. They are just always set to 1 but they are publicly accessible. For example `IntRange` is also an `IntProgression` with [step set to 1](https://github.com/JetBrains/kotlin/blob/924c28507067cbfbf78a6509ea89eabe496e34ca/libraries/stdlib/src/kotlin/ranges/PrimitiveRanges.kt#L54).

```kotlin
val r = 1..10 // this creates a IntRange
val s = 1..10 step 10 // this creates a IntProgression

println(r.step) // prints 1
```

May be we can also do the same i.e `Range` can be a `Progression` with step equal to 1.

**Comment by SupunS** [comment]
This issue can now be closed as completed, since the feature was added in the following PRs:
- https://github.com/onflow/cadence/pull/2523
- https://github.com/onflow/cadence/pull/2892

The remaining improvements https://github.com/onflow/cadence/issues/2886 and https://github.com/onflow/cadence/issues/2870, depend on some general improvements to the Cadence checker and interpreter, hence would need to be addressed separately, and don't need to be part of this issue.
