### ISSUE TITLE
External Mutability Improvements

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#2638]
```[tasklist]
### FLIPs
- [ ] https://github.com/onflow/flips/pull/89
- [ ] https://github.com/onflow/flips/pull/86
- [ ] https://github.com/onflow/flips/pull/97
- [ ] https://github.com/onflow/flips/pull/94
``` 

```[tasklist]
### Tasks
- [ ] https://github.com/onflow/cadence/issues/2534
- [ ] https://github.com/onflow/cadence/issues/2535
- [ ] https://github.com/onflow/cadence/issues/2536
- [ ] https://github.com/onflow/cadence/issues/2647
- [ ] https://github.com/onflow/cadence/issues/2677
- [ ] https://github.com/onflow/cadence/issues/2684
```
