### ISSUE TITLE
Cadence 1.0 (formerly known as "Stable Cadence")

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#2642]
```[tasklist]
### 🚨 Testnet Upgrade blockers
- [x] Release new Emulator with https://github.com/onflow/flow-go/pull/6422
```

```[tasklist]
### Features
```

```[tasklist]
### Tech Debts / Chore
- [ ] https://github.com/onflow/cadence/issues/3335
- [ ] https://github.com/onflow/cadence-lang.org/issues/166
- [ ] https://github.com/onflow/cadence/issues/3268
- [ ] https://github.com/onflow/cadence/issues/2503
- [ ] https://github.com/onflow/cadence/issues/2719
- [ ] Remove uses of and definitions for AuthAccount/PublicAccount types after migrations
- [ ] Account export (https://www.notion.so/dapperlabs/Cadence-Implementation-Sync-Notes-Agenda-640389e72df942668d89deadd8d291de?pvs=4#c854ad5cc91b4a88922557449f5be3b9)
- [ ] https://github.com/onflow/cadence/issues/2766
- [ ] https://github.com/onflow/cadence/issues/2726
- [ ] Improve documentation: https://github.com/onflow/cadence-lang.org/issues/26
- [ ] https://www.notion.so/dapperlabs/Cadence-Implementation-Sync-Notes-Agenda-640389e72df942668d89deadd8d291de?pvs=4#72e9a6394ad44c3883f5d515772f95e3
- [ ] Improve documentation: Full pass of language reference, follow up on e.g. tutorial
- [ ] https://github.com/onflow/cadence/issues/3108
- [ ] https://github.com/onflow/cadence/issues/3113
- [ ] https://github.com/onflow/cadence/issues/3114
- [ ] https://github.com/dapperlabs/cadence-internal/issues/187
- [ ] https://github.com/onflow/cadence/issues/3206
```

```[tasklist]
### Maybe? (on-hold)
- [ ] https://github.com/onflow/cadence/issues/2170
- [ ] https://github.com/onflow/cadence/issues/2953
- [ ] https://github.com/dapperlabs/cadence-internal/pull/116
```

**Comment by turbolent** [comment]
@onflow/cadence I wonder if we maybe want to clear out all the done items in the list, to only leave what is left, so it is easier to see?

**Comment by SupunS** [comment]
I moved some on-hold items to a separate section `Maybe?(on-hold)`, to make it more clear on the "must do" items.

**Comment by j1010001** [comment]
all relevant remaining issues transferred to https://github.com/onflow/cadence/issues/3906
