### ISSUE TITLE
Implement Custom Destructor Removal

### ISSUE THREAD

**Issue by j1010001** [onflow/cadence#2790]
Implementation of https://github.com/onflow/flips/pull/95 
Includes Default event emission
```[tasklist]
### Tasks
- [ ] https://github.com/onflow/flips/pull/131
- [ ] https://github.com/onflow/cadence/pull/2789
- [ ] https://github.com/onflow/cadence/pull/2799
- [ ] https://github.com/onflow/cadence/pull/2812
- [ ] https://github.com/onflow/cadence/pull/2817
```
