### ISSUE TITLE
[EPIC] Enable testing of contract update to Cadence 1.0 in Emulator

### ISSUE THREAD

**Issue by j1010001** [onflow/cadence#2947]
### Issue to be solved

Why: Developers need to test their ability to upgrade their existing contract to Cadence 1.0 version. When we release Emulator running Cadence 1.0, this would not be possible because if the upload of a contract that does not parse/typecheck with Cadence 1.0 will fail. 

This step is required to collect data for the next stage, described in https://github.com/onflow/cadence/issues/2865.

```[tasklist]
### Tasks for Emulator 1.0 RC1 release (enables dapp testing):
- [x] Enable devs to deploy old (0.4x-based) Cadence contracts to emulator and then upgrade to C1.0. This will likely require emulator-only contracts.add method which skips type checking and enables any code to be uploaded, and parser that can parse contracts based on both v04 and 1.0 versions to perform the update restrictions. This requires the update checker to be able to parse both v0.42 and 1.0 contract versions.
- [ ] https://github.com/onflow/cadence/pull/3157
- [ ] https://github.com/onflow/cadence/pull/3158
- [ ] https://github.com/onflow/flow-go/pull/5486
- [ ] https://github.com/onflow/flow-go/pull/5479
- [ ] https://github.com/onflow/flow-cli/issues/1433
- [x] Release this emulator build to community - this enables devs to test their contract upgrade to C1.0.
```

**Comment by j1010001** [comment]
Required for: https://github.com/onflow/flow-emulator/issues/468

**Comment by j1010001** [comment]
Can be closed after the new Emulator build is released.

**Comment by turbolent** [comment]
Is the requirement for closing this issue that the updated update checker has been completed, or is that a separate issue/milestone?

**Comment by j1010001** [comment]
> Is the requirement for closing this issue that the updated update checker has been completed, or is that a separate issue/milestone?
> 
> I assume that work is part of #2865, in which case this issue can be considered in-review/done.

No, let's close this when the first version of this is out and create a new issue if the upgrade checker needs adjustments.

**Comment by SupunS** [comment]
I guess we can close this issue now?

**Comment by turbolent** [comment]
Yeah, I think we can close this now, given there's no known work left to be done. 🎉 👏 

We can maybe leave #3098 open until it's been confirmed that the latest CLI preview release works as expected.
