### ISSUE TITLE
Run full Cadence 1.0 migration on TN state

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#3096]
```[tasklist]
### Tasks
- [x] Cadence 1.0 migration: Errors when worker count >1
- [x] Transfer, called by remove, insert, etc., loads types, which might be unmigrated/unsupported: empty intersection types are invalid: https://github.com/onflow/cadence/pull/3138
- [x] Static types of containers need to get migrated too: https://github.com/onflow/cadence/pull/3141
- [x] Ensure nested containers are properly (recursively) migrated: https://github.com/onflow/cadence/pull/3141 and https://github.com/onflow/cadence/pull/3142
- [ ] https://github.com/onflow/flow-go/issues/5485
- [ ] https://github.com/onflow/cadence/issues/3153
- [ ] https://github.com/onflow/cadence/issues/3149
- [x] Clean up TN service account: Prune random beacon history
- [ ] https://github.com/onflow/cadence/pull/3158
- [ ] https://github.com/onflow/cadence/pull/3157
```

**Comment by turbolent** [comment]
For investigating the concurrency issues, I tried building the `util` binary with the race detector on, but it reported no issues:

```sh
CGO_ENABLED=1 \
GOOS=linux \
GOARCH=amd64 \
CC="zig cc -target x86_64-linux-musl" \
CXX="zig c++ -target x86_64-linux-musl" \
go build -v --tags "netgo,osusergo" -race -ldflags "-extldflags=-static"
```

**Comment by turbolent** [comment]
For the empty intersection type loading issue, I opened #3138, which so far has a reproducer for one particular case where the type loading occurs (`DictionaryValue.Insert` in `StorageMigration.MigrateNestedValue`).

I'm not really sure how to proceed here. Disabling type checks, like `checkContainerMutation` isn't sufficient, because e.g. `CompositeValue.Transfer` calls `CompositeValue.IsResourceKinded`, which isn't just a run-time check, but required to distinguish between the struct vs resource code path of transferring (copy vs move).

The best idea I came up so far is rewriting the static type of a container value (e.g. dictionary, array), before migrating the nested value inside of it, i.e. before calling `Remove`/`Insert`, and before the related `Transfer` calls occur, which convert the static type.

**Comment by turbolent** [comment]
I wonder if we can integrate the intersection type rewriting and entitlements migration code directly into `interpreter.ConvertStaticToSemaType`. 

I tried just performing the intersection type rewriting there, and none of the tests break, except for the entitlements migration, which looses the necessary information it needs (legacy intersection type). Maybe also adding the entitlements migration there will fix that last issue?

**Comment by janezpodhostnik** [comment]
About *Errors when worker count >1*

not 100% sure they are all related to the same thing (its likely), but one of the problems is that the migration code currently doesn't support creating slab indexes from multiple goroutines. This can be fixed by either adding a locking mechanism or some channel magic. 

I will take a look.

**Comment by fxamacker** [comment]
> About Errors when worker count >1
>
> not 100% sure they are all related to the same thing (its likely), but one of the problems is that the migration code currently doesn't support creating slab indexes from multiple goroutines. This can be fixed by either adding a locking mechanism or some channel magic.

Unless I'm mistaken, `worker count > 1` means `n` workers processing `n` accounts concurrently.

Slab indexes are per account.  I think we might only have a problem to generate slab index if multiple goroutines migrate the same account.

**Comment by turbolent** [comment]
I had a look at `AtreeRegisterMigrator`, and the function that generates the new payloads from the snapshot's, `validateChangesAndCreateNewRegisters`, looks different from `MergeRegisterChanges` in the Cadence 1.0 migration. Are there maybe some cases we're not properly handling yet?

**Comment by turbolent** [comment]
Cross posting from Discord, Re: Does the migration pipeline properly migrate nested containers? 

The example I thought of was: 
Given an outer container (e.g. dictionary) and and inner one, both their static types must be updated (by the static type migration, and again by the entitlements migration).
Both the static type migration (https://github.com/onflow/cadence/pull/3141/files#diff-1b50282851963b6af7e8c0baf33a448c9b6fdb4d405de6182626484310c8b5ffR151-R168) and the entitlements migration (https://github.com/onflow/cadence/blob/2dd12d390768c70d5c7277836d5b9d29ff339d23/migrations/entitlements/migration.go#L256-L285) create/return a new/replacement value, and do not recursively call the migration.

From what I can see (but I might be missing something), the "outer" storage migration (StorageMigration) only mutates the existing value to be migrated (https://github.com/onflow/cadence/blob/2dd12d390768c70d5c7277836d5b9d29ff339d23/migrations/migration.go#L245-L336).
I'd assume to be that the outer storage migration code either 
performs a post-order "traversal"/migration, i.e. migrates the child values of the container first, and then updates the outer replacement (if any); or
performs a pre-order  "traversal"/migration, i.e. migrates the value (in this case container) first, then the children

I wasn't quite sure if we properly handle it and it would be good to have a test case for it (maybe we have one already)

**Comment by SupunS** [comment]
Added some tests and improved the comments here: https://github.com/onflow/cadence/pull/3142

**Comment by turbolent** [comment]
@janezpodhostnik @fxamacker I reran the util with race detector enabled on the machine and this time it reported data races while grouping accounts. Opened onflow/flow-go#5485. Could you please have a look?

**Comment by turbolent** [comment]
Adding atree storage health checks to the tests of the migrations in #3144 shows errors. 

My hunch is that the container re-creation, as done by the static type and entitlement migration, is incorrect: We're just creating a new dictionary, and insert the elements of the container directly into it – we probably need to properly remove them from the old container, which transfers them to the "stack", and then insert them into the new container

**Comment by fxamacker** [comment]
> @janezpodhostnik @fxamacker I reran the util with race detector enabled on the machine and this time it reported data races while grouping accounts. Opened https://github.com/onflow/flow-go/issues/5485. Could you please have a look?

@turbolent I opened PR to fix the data race and added a test to reproduce it:
- https://github.com/onflow/flow-go/pull/5488

The PR targets main branch since it is a bugfix.

**Comment by turbolent** [comment]
Running the migration with the latest fixes also reports a "Go panic" for an out-of-bound index:

```
ERR failed to run StorageMigration in account 9eca2b38b18b5dfe, domain contract, key FlowDKG: runtime error: index out of range [0] with length 0 migration=cadence-value-migration migration_index=0
```
@SupunS Could we maybe improve the storage migration to include a stack trace when we recover from panics, so we can pinpoint the problem?

The migration also runs in to "slab not found" errors, but those are probably due to the bugs we have already reported by the atree storage health checks:

```
ERR failed to run StorageMigration in account 9eca2b38b18b5dfe, domain contract, key FlowIDTableStaking: slab (0x9eca2b38b18b5dfe.49614) not found: slab not found for stored value migration=cadence-capability-value-migration migration_index=0
```

Finally, the progress logs for storing the final trie seemed odd, cc @onflow/flow-cadence-execution:

```
INF storing 9-th sub trie roots progress 6906506/5755421 (120.0%) elapsed: 4m17s, eta 0s checkpoint_file=/var/flow/c1/root.checkpoint trie_count=1 version=6
```

**Comment by turbolent** [comment]
@fxamacker In the migrations, we need to often update the static types of values, including containers (array, dictionaries, composites), i.e. the type info of atree arrays and ordered maps. 

Do you think we could add support for changing the type info? 

I saw that `OrderedMap` has `Type()` to get the `TypeInfo`, which in turn uses `MapSlab.ExtraData()`. There is also a `MapSlab.SetExtraData()`, but it's not (yet) exposed via a `OrderedMap.SetType()`.

**Comment by fxamacker** [comment]
> Do you think we could add support for changing the type info of atree arrays and ordered maps?

@turbolent Yes, I can add `Array.SetType()` and `OrderedMap.SetType()` in atree.  

Are these functions needed for both atree-inlining branch and master branch in atree repo?

**Comment by fxamacker** [comment]
> Do you think we could add support for changing the type info of atree arrays and ordered maps?

@turbolent I opened PRs at onflow/atree to add `SetType` for atree containers (without inlining):
- https://github.com/onflow/atree/issues/372
- https://github.com/onflow/atree/issues/373

> Yes, those functions will be needed for both the current atree version used on master (higher priority)

Since Cadence master branch is using atree `feature/stable-cadence` branch, I made the new PRs target `feature/stable-cadence` branch (instead of master).

```
github.com/onflow/atree v0.6.1-0.20230711151834-86040b30171f
```

> in the register-inlining version of atree used in the atree register-inlining branch (we can port the functions there later)

The same functions probably can't be ported to atree-inlining version because inlined container needs to notify parent container so parent container slab can be persisted with new inlined static type information.  

I will open new PRs to add `SetType` implemented differently for atree-inlining version.

**Comment by turbolent** [comment]
@fxamacker Awesome! Thank you for adding these 👏  👌

**Comment by turbolent** [comment]
The TN state service account is massive (5GB!), because of the random beacon history, see https://discord.com/channels/613813861610684416/1215015019260158022. I upgraded my machine at home to 64GB of memory and that still doesn't seem to be enough. 

I'll try to add a migration to the beginning of the migration pipeline which prunes the random beacon history.

**Comment by turbolent** [comment]
All items so far have been addressed, and this issue is getting long.

Closing and opening a new issue for follow-up work that was discovered

**Comment by fxamacker** [comment]
Nice! :clap:
