### ISSUE TITLE
Cadence Technical Foundations

### ISSUE THREAD

**Issue by j1010001** [onflow/cadence#3595]
### Why (Objective)

High-quality technical foundations (well designed, clear code with no tech-debt, bugs & workarounds) is more efficient to build on and less prone to unintended behaviour leading to errors.

Aside from technical debt, we also had to pause FLIPs. It puts us in a bad light if we ask the community for input, but then let proposals get stale, some are years (!) old. We should be good citizens in the community.

We also have a number of bugs in the codebase. Features sometimes do not work as intended. This leads to frustration of developers, and might even block them from implementing their use case. Worst case the bugs are security issues.

It is essential to deal with those issues before we make further changes to Cadence.

### How will we measure success (Key Results) ?

1. Completing the Bugs & tech-debt task-lists.
2. Automation to detect breaking changes in Cadence pre-release is updated to cover all relevant onflow repos.
3. No open Flips from past years. At the start of the cycle, there are [7]

```[tasklist]
### Bugs
- [ ] https://github.com/dapperlabs/cadence-internal/issues/187
- [ ] https://github.com/dapperlabs/cadence-internal/pull/259
- [ ] https://github.com/dapperlabs/cadence-internal/pull/261
- [ ] https://github.com/dapperlabs/cadence-internal/pull/242
- [ ] https://github.com/dapperlabs/cadence-internal/pull/257
- [ ] https://github.com/dapperlabs/cadence-internal/pull/258
```

```[tasklist]
### Infrastructure to ensure backward-compatibility
- [ ] https://github.com/onflow/cadence/issues/3608
```

```[tasklist]
### Tech-Debt
- [ ] #2766
- [ ] #2719
- [ ] https://github.com/onflow/cadence/issues/2503
- [ ] https://github.com/onflow/cadence/issues/2566
- [ ] https://github.com/onflow/cadence/issues/526
- [ ] https://github.com/onflow/cadence/issues/3135
- [ ] https://github.com/onflow/flow-go/pull/6572
- [ ] https://github.com/onflow/cadence/pull/3642
- [ ] https://github.com/onflow/cadence/pull/3643
- [ ] https://github.com/onflow/cadence/pull/3652
- [ ] https://github.com/onflow/cadence/pull/3651
- [ ] https://github.com/onflow/cadence/pull/3646
- [ ] https://github.com/onflow/cadence/pull/3650
- [ ] https://github.com/onflow/cadence/pull/3647
- [ ] https://github.com/onflow/cadence-internal/issues/280
```

```[tasklist]
### Clean-up open Flips
- [ ] https://github.com/onflow/cadence/issues/3615
- [ ] https://github.com/onflow/cadence/issues/3210
```

```[tasklist]
### Stretch goals
- [x] Extend Source compatibility suite to selected community projects: https://github.com/onflow/cadence/pull/3644
- [ ] #3114
- [ ] https://github.com/onflow/cadence/issues/2630
- [ ] https://github.com/onflow/cadence/issues/3624
```
