### ISSUE TITLE
Community outreach (Marketing, Docs, Examples)

### ISSUE THREAD

**Issue by j1010001** [onflow/cadence#3596]
### Why (Objective)

To use Cadence to it's full potential, developers need clear content, complete documentation and examples of it's features and how to use them, demonstrating the possibilities.

- Deliver on Crescendo promise - all content owned by Cadence team is updated to cover changes delivered in C1.0.
- Prioritize helping 4D Marketing, Education and Product teams when they need Cadence expertise, so that content production is not blocked.
- Cadence team becoming more familiar with  developer journey, so they can better understand developer needs.

### How will we measure success (Key Results) ?

- Content production is not blocked by capacity on Cadence team.
- Having visibility into cadence-lang.org usage by integrated analytics tool.
- Cadence-lang.org reviewed & updated - no known gaps in docs.
- Cadence docs linked to examples.
- Submitted Cadence talk proposal to 3 conferences.
- Cadence dev team went through the developer journey end-end.

## DACI
| Role | Assigned |
| ------ | ---------|
| Driver | @turbolent |
| Approver | @roham |
| Consulted| @gregsantos , @SeanRobb |
| Informed| Cadence team, 4D team |

```[tasklist]
### collaboration: Cadence <> 4D <> Marketing <> Education
- [ ] https://github.com/onflow/cadence/issues/3598
- [x] Support Brian on educational content
- [x] Sync on tutorials in: https://github.com/onflow/cadence-lang.org/issues/26
```

```[tasklist]
### Tasks - Cadence team
- [ ] https://github.com/onflow/cadence/issues/3645
- [ ] https://github.com/onflow/cadence/issues/3639
- [ ] Re-submitt talk proposal to few conferences (IPFS camp ? - Anthony)
```
```[tasklist]
### Docs
```

```[tasklist]
### Stretch-goals: collaboration: Cadence <> 4D <> Marketing
```
