### ISSUE TITLE
Discovery of gaps in our dev journey

### ISSUE THREAD

**Issue by j1010001** [onflow/cadence#3645]
time-boxed, Cadence devs dog-fooding the dev experience.

Brian's doc for the learning app: https://docs.google.com/document/d/1_c6fqqNYJnEZLcbhzkQ2nweXGrvkKtZLggCxjABY2Hc/edit?tab=t.0#heading=h.9yxznnjnjj8i

```[tasklist]
### Tasks
- [ ] https://github.com/onflow/cadence-tools/pull/445
- [ ] https://github.com/onflow/flow-cli/pull/1801
- [ ] https://github.com/onflow/flow-cli/pull/1802
- [ ] https://github.com/onflow/flow-cli/issues/1815
- [ ] https://github.com/onflow/cadence-lang.org/issues/173
- [ ] https://github.com/onflow/cadence-tools/issues/447
- [ ] https://github.com/onflow/cadence-tools/issues/448
- [ ] https://github.com/onflow/cadence-tools/issues/446
- [ ] https://github.com/onflow/vscode-cadence/issues/563
- [ ] https://github.com/onflow/docs/issues/988
- [ ] https://github.com/onflow/flow-playground/issues/816
- [ ] https://github.com/onflow/cadence/issues/3671
```

**Comment by bluesign** [comment]
I can add one thing I still cannot manage to find the correct way to do : 

```cadence 
var a : String?? = "deniz" // one or more optional 
var b: String? = .... ( get from a to b ) 
```

**Comment by turbolent** [comment]
@bluesign This issue is meant for the Cadence team to use Cadence and the Flow tools to build something, to experience them as developers do, and find gaps and bugs along the way. If you have a problem, please open a separate issue, thanks!

**Comment by j1010001** [comment]
Discovery completed.
