### ISSUE TITLE
Cadence Compiler - phase 2

### ISSUE THREAD

**Issue by j1010001** [onflow/cadence#3692]
**Cadence compiler project end-goal (Long-term):**

Build Cadence compiler and VM to enable execution of Cadence code as efficiently as possible (as close to the native machine code of the used execution node architecture as practical), to achieve the maximum transaction throughput on the execution node.

**Phase 2 goal:**

Complete Cadence compiler & VM using custom bytecode. This is middle-ground between current execution using Cadence Interpreter and the end-goal with compilation + VM to native machine code.
Replace the Cadence interpreter with concurrent on-chain compilation of contracts + transactions and their execution by custom-bytecode VM. 

Note:The custom bytecode is designed to achieve this goal with minimal complexity, mapping as closely as possible to the existing Cadence language functionality/operations, which makes it possible to partially reuse existing interpreter code in the custom VM.

**Phase 2 Outcomes (Key results):**

- Validate execution stack using on-chain compilation and custom bytecode VM on backwards-compatibility workflow by integrating with VN execution (chunk data packs, no storage layer).
- Validate execution stack using on-chain compilation and custom bytecode VM on EN by re-executing blocks (integrated into EN, using mTrie+Atree storage layer for execution)
- Deliver first version of execution stack using on-chain compilation and custom bytecode VM to production, enabling gradual targeted compiler + VM optimizations to  move the execution stack to lower-level / native code.
- Custom bytecode provides new abstraction layer in the execution stack, which improves our ability to add new features into the language without braking promise of backwards-compatible runtime.
- Reduce the execution stack complexity
    - Metering can be performed at the bytecode level, which is much easier than the current approach with instrumentation of interpreter functionality which is much larger surface to cover.
- We are not expecting significant performance improvement in this phase, the goal is to achieve correctness parity & comparable performance with the existing Cadence interpreter.

**Phase 2 timeline:**

Q1 2025 - brake down and estimate remaining Cadence interpreter operations to be implemented, discuss & plan the integration of concurrent compilation & VM into the execution node stack. Provide estimation of remaining effort for compiler phase 2 before the end of Q1 2025. Start implementation.

## DACI

| Role | Assigned |
| ------ | ---------|
| Driver |  technical: @SupunS , EM: @j1010001  |
| Approver | @dete |
| Consulted| @turbolent, @Kay-Zee, @jsproz  |
| Informed| Flow Engineering team |

```[tasklist]
### Main Tasks (WIP)
- [ ] https://github.com/onflow/cadence/issues/3742
- [ ] https://github.com/onflow/cadence/issues/3733
- [ ] https://github.com/onflow/cadence/issues/3721
- [ ] https://github.com/onflow/cadence/issues/3697
- [ ] https://github.com/onflow/cadence/issues/3696
- [ ] https://github.com/onflow/cadence/issues/3688
- [ ] https://github.com/onflow/cadence/pull/3702
```

```[tasklist]
### Stretch-goals
- [ ] https://github.com/onflow/cadence/issues/3691
- [ ] https://github.com/onflow/cadence/issues/3769
```

**Notes**
Based on internal notes: https://www.notion.so/flowfoundation/Compilation-Discussion-1441aee1232480c897aed36c8f763e30

**Phase 1 outcomes (completed):**
- Better understanding of what target(s) to consider - Ruled out Move VM and WebAssembly.
