### ISSUE TITLE
Next storage optimizations

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#833]
An umbrella epic for the storage optimizations scheduled starting Apr 26th

**Comment by fxamacker** [comment]
- [ ] Issue #742 Pre-allocate and reuse value-path during preparation for encoding.  Benchmark comparisons look promising.
 - [ ] Issue #832 Increase range of various max limits allowed in fxamacker/cbor.
 - [ ] Issue #838 Optimize Address.Bytes() to improve encoding speed of storage layer.  Benchmark comparisons look promising.
